version: '2'

services:

    api:
      restart: always
      build:
        context: ./api
        dockerfile: Dockerfile
      environment:
        - FLASK_ENV=production
      depends_on:
        - postgres
      expose:
        - "8000"
      volumes:
        - tmp-data:/tmp/
      command: /usr/local/bin/gunicorn wsgi:app -b 0.0.0.0:8000 -t 120


    nginx-proxy:
      restart: always
      build:
        context: ./nginx-proxy/
      ports:
        - "80:80"
        - "443:443"
      volumes_from:
        - api


    postgres:
      restart: always
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      expose:
        - "5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
    tmp-data:

